### ISSUE TITLE
install.lua throws segfault for fwrite()

### ISSUE THREAD

**Issue by hwhw** [koreader/android-luajit-launcher#15]
On my Android 4.4 phone, install.lua throws a segfault. The backtrace points to fwrite. We don't check if fopen(..., "wb") succeeds, so I guess it doesn't. Maybe we need another permission, maybe some other thing. I'll investigate, but it will take ~24 hours.

**Comment by pazos** [comment]
I don't think this is still an issue, pinging @hwhw for confirmation

**Comment by hwhw** [comment]
I think I'm unable to test this - my Android 4.4 phone is long gone... Let's close this.
