### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Frenzie** [koreader/android-luajit-launcher#155]
If you add PNG files in `fastlane/metadata/android/en-US/images/phoneScreenshots/`, F-Droid will use them automatically when publishing the next release (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository)).

_Originally posted by @Rudloff in https://github.com/koreader/koreader/issues/2040#issuecomment-486429411_

**Comment by pazos** [comment]
Need a few screenshots, like the ones in https://github.com/koreader/koreader-artwork, but with the form factor of a phone, for example:

![3](https://user-images.githubusercontent.com/975883/61890608-19dca300-af08-11e9-8cb0-c50b66a2374b.png)

Of course having the same image contents its a plus!

Also I'm not sure if the fastlane/metadata/android/en-US/images/phoneScreenshots/ should be placed on this repository or in https://github.com/koreader/koreader

@Rudloff ¿?

**Comment by Rudloff** [comment]
The files should be in https://github.com/koreader/koreader.git (because it is what we consider the main repository).

**Comment by pazos** [comment]
Thanks!, closing this issue. Using https://github.com/koreader/koreader/issues/4904 instead
