### ISSUE TITLE
How can I build this project in windows?

### ISSUE THREAD

**Issue by wo4chenkewen** [koreader/android-luajit-launcher#212]
Does this project support to build in windows environment? When I use my android studio to build this project in windows environment, a error occurs which complains that libluajit-5.1.a is missing. How could I deal with problem. Does I need to install lua environment first? or Cygwin environment or other sth similarly.

**Comment by Frenzie** [comment]
I wouldn't count on it, but note that the README lists the steps to compile LuaJIT:

https://github.com/koreader/android-luajit-launcher#starting

**Comment by pazos** [comment]
You can get libluajit-5.1.a for both armeabi-v7a and x86 and place them in jni/luajit/build/$(arch)/lib. You'll need to place headers in jni/luajit/build/$(arch)/include.

With static libraries and headers in place you can build the project with both `gradlew.bat` and android studio in Windows.

**Comment by wo4chenkewen** [comment]
> You can get libluajit-5.1.a for both armeabi-v7a and x86 and place them in jni/luajit/build/$(arch)/lib. You'll need to place headers in jni/luajit/build/$(arch)/include.
> 
> With static libraries and headers in place you can build the project with both `gradlew.bat` and android studio in Windows.

I mean I how could I build luaJit in windows? or I just get "libluajit-5.1.a for both armeabi-v7a and x86" from website.  Does I need use this link https://github.com/LuaJIT/LuaJIT/tree/f0e865dd4861520258299d0f2a56491bd9d602e1
to get the luajit, and then compile it to generate the libluajit-5.1.a. forgive me this stupid question, for I'm a beginner for lua.

**Comment by wo4chenkewen** [comment]
The reason I get notice this project,  I notice that this project uses kind of new design patterns to generate a app. That is a NativeActivity. I'm curious about it how does the project organized or designed. I wanna learn sth from your project. So, thank you sharing the project.

**Comment by Frenzie** [comment]
Calling it a design pattern possibly implies a bit more than there is. It's not that someone thought this was a great way to build an Android app or even necessarily a cross-platform app. There was an existing app (using decades old design patterns, so to speak) and this seemed like a fairly decent way to port it to Android.

LuaJIT is a very interesting tool of course, also used in https://www.love2d.org/ for example.

**Comment by pazos** [comment]
Now I just checked. To build LuaJIT on windows you'll need cygwin or similar posix tools. I don't think this project can be built on windows at all without extensive work (because even when you manage to build luajit you need to link it to the native glue).
