### ISSUE TITLE
当lua代码出现死循环 我该怎么停止运行 这个时候button没有反应

### ISSUE THREAD

**Issue by tghjnjvg** [koreader/android-luajit-launcher#228]
当lua代码出现死循环 我该怎么停止运行 这个时候button没有反应

**Comment by Frenzie** [comment]
According to Google Translate:

> When the Lua code appears an endless loop, how can I stop it?

I don't know what that means. An infinite loop where or how? If there's an infinite loop, you probably put it there. ;-)

**Comment by tghjnjvg** [comment]
such as
while true:
   print("")
how can i close it

**Comment by Frenzie** [comment]
You would put in some condition that *may* evaluate to true. I suggest you consult a tutorial or some kind of forum targeted at beginning programmers.

**Comment by tghjnjvg** [comment]
我不是这个意思 我想能不能多线程运行lua代码 然后关闭某个线程然后来强制关闭lua代码运行的线程

**Comment by Frenzie** [comment]
> I do n’t mean this. I want to be able to run lua code in multiple threads, then close a thread, and then forcefully close the thread running lua code.

In essence that's still a generic Lua/LuaJIT question, from built-in coroutines to one of the many libraries like Lua Lanes. You do threads however you want to do threads; it doesn't really have anything to do with this repo.

Depending on what you're looking for, perhaps LÖVE might be useful.
https://love2d.org/wiki/love.thread
