### ISSUE TITLE
cannot build luajit

### ISSUE THREAD

**Issue by ildar** [koreader/android-luajit-launcher#262]
excerpt:
```
+ make -C luajit-2.0 install 'HOST_CC=gcc -m32' 'CFLAGS=-O2 -pipe' 'HOST_CFLAGS=-O2 -pipe -mtune=generic' LDFLAGS= HOST_LDFLAGS= TARGET_CFLAGS= TARGET_LDFLAGS= 'CROSS=/tmp/a/ndk/18.1.5063045//toolchains/arm-linux-androideabi-4.9/prebuilt/*/bin/arm-linux-androideabi-' 'TARGET_FLAGS=--sysroot /tmp/a/ndk/18.1.5063045//platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8' TARGET_SYS=Linux DESTDIR=/usr/src/android-luajit-launcher/jni/luajit/build/armeabi-v7a PREFIX=
make: Entering directory '/usr/src/android-luajit-launcher/jni/luajit/luajit-2.0'
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/usr/src/android-luajit-launcher/jni/luajit/luajit-2.0/src'
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--fix-cortex-a8: 'linker' input unused [-Wunused-command-line-argument]
HOSTLINK  host/minilua
/usr/bin/ld.default: skipping incompatible /usr/lib64/gcc/x86_64-alt-linux/9/../../../libm.so when searching for -lm
/usr/bin/ld.default: cannot find -lm
/usr/bin/ld.default: skipping incompatible /usr/lib64/gcc/x86_64-alt-linux/9/libgcc.a when searching for -lgcc
/usr/bin/ld.default: cannot find -lgcc
/usr/bin/ld.default: cannot find libgcc_s.so.1
/usr/bin/ld.default: skipping incompatible /usr/lib64/gcc/x86_64-alt-linux/9/libgcc.a when searching for -lgcc
/usr/bin/ld.default: cannot find -lgcc
collect2: error: ld returned 1 exit status
```
please help.

**Comment by Frenzie** [comment]
The simple answer is to use gcc, not clang. That being said, I'm not immediately sure why luajit/minilua isn't just going along with using clang there.

**Comment by ildar** [comment]
This is nice to know about. But I don't see a handle to change it with.
A hint, please?

**Comment by Frenzie** [comment]
I simply mean that's what your error messages indicate. Are you using Android Studio?

**Comment by ildar** [comment]
no, pure command line in a chroot.

**Comment by Frenzie** [comment]
You could try something like CC=arm-linux-androideabi-gcc

**Comment by ildar** [comment]
nope.
$
/tmp/a/ndk/18.1.5063045//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
-v
Android (4751641 based on r328903) clang version 7.0.2 (
https://android.googlesource.com/toolchain/clang
003100370607242ddd5815e4a043907ea9004281) (
https://android.googlesource.com/toolchain/llvm
1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
Target: arm--linux-android
Thread model: posix
InstalledDir:
/tmp/a/ndk/18.1.5063045//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../../../../llvm/prebuilt/linux-x86_64/bin
Looks like NDK version 18.1.5063045 doesn't fit.

**Comment by Frenzie** [comment]
Should be safe with r15c. I think it should be possible though. Maybe @pazos knows otoh.

**Comment by pazos** [comment]
We use NDK15c to keep compatibility with platform-14.

This project can be compiled with newer NDKs but you need to adapt mk-luajit.sh accordly based on updated instructions https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/install.html#L405

This applies to android-luajit-launcher. KO needs more work to be compatible with newer toolchains

**Comment by ildar** [comment]
Thank you for the hint.
>
> It should be easy to fix as linker used is the wrong one. I'll check this
idea tomorrow and report back

**Comment by ildar** [comment]
I am sorry but that was my local misconfiguration.
The root reason for the error was that my host compiler (which is x86_64)
couldn't find some files for `-m32`. So to go on one has to install the
32bit target host compiler and arm target compiler that NDK provides. This
is what's required ATM. Maybe some more to come: I didn't finish yet.

**Comment by pazos** [comment]
feel free to keep us updated. Closing as this isn't really an issue

**Comment by ildar** [comment]
Just FTR: quick fix for building with NDK20 / clang
<https://github.com/ildar/android-luajit-launcher/commit/bcad26725798371660d6d2dc6abbe9d84698a457>
here:
https://github.com/ildar/android-luajit-launcher/commit/bcad26725798371660d6d2dc6abbe9d84698a457
