### ISSUE TITLE
Differenciate between rocks and fdroid flavors.

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#304]
I wish I could rename the package name of the fdroid flavor from `org.koreader.launcher` to `org.koreader.launcher.fdroid`. Sadly this is not easy without breaking a bunch of stuff we don't control. 

So I was thinking about using a diferent icon color (paired with fdroid logo) Something like 
![icon](https://user-images.githubusercontent.com/975883/117513554-41dcaf80-af92-11eb-93fb-64e22edd41b4.png)

This will keep the disadvantages of sharing the same package name (error installing packages with different signatures) but at least the user could have a clue on why this happens.

**Comment by NiLuJe** [comment]
It's been incredibly helpful for debug builds in my experience, so, yeah, sounds good ;).

**Comment by Frenzie** [comment]
I'm not sure about the color, but a little F-Droid overlay or something could certainly make sense.

**Comment by pazos** [comment]
> I'm not sure about the color, but a little F-Droid overlay or something could certainly make sense.

An overlay in the icon? Not sure if that will look nice & clean. The color looks good to me, but I have no idea if it goes against the brand :tm: 

BTW: related to change package name: https://forum.f-droid.org/t/change-package-name-app-id-of-an-app-on-the-main-repo/13543

**Comment by Frenzie** [comment]
Yes, the Brand™ is pretty much what I mean. But not so much in a brand sense as in a user just glancing for the right color and not finding it sense.

**Comment by NiLuJe** [comment]
Admittedly, a shift from cyan to sky blue isn't that much of a stretch?

**Comment by pazos** [comment]
Since renaming the app package from `org.koreader.launcher` to `org.koreader.launcher.fdroid` is possible having both apps installed at the same time is possible too. Then a change in the icon is needed for figuring out which is which.

I suppose is not a big issue to have two identical KOReader icons on the launcher :p.

The overlay stuff is a bit different to implement for adaptative icons, since the icons in all flavors share the same foreground: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/res/mipmap-xxxhdpi/icon_foreground.png

**Comment by Frenzie** [comment]
It just seems a bit weird to me to have a different color for something that's exactly the same except for some minor technical detail. As a user I'd expect a different UI experiment, a v2.0, or something.

**Comment by poire-z** [comment]
I'm fine with the icons having different colors - and if I were a f-droid user, I'd prefer that color change to an icon with some added "+" or "v2" or other cosmetic usually ugly.
(And I quite like that blue icon :) getting tired of our pale green :)
