### ISSUE TITLE
Poke Pro still unsupported

### ISSUE THREAD

**Issue by EyalGol** [koreader/android-luajit-launcher#358]
A few days ago I made PR #357 that was merged, I installed the latest nightly (2022.01-50), and after a quick test poke_pro is still "unsupported"

[compatibility_test.log](https://github.com/koreader/android-luajit-launcher/files/7941760/test.log)
[adb.log](https://github.com/koreader/android-luajit-launcher/files/7941787/adb.log)

**Comment by pazos** [comment]
It wasn't merged yet on main repo.

**Comment by EyalGol** [comment]
Oh okay, not very familiar with how this project is managed.
Maybe in the future, I will get into it, I have some plugin ideas.
thanks

**Comment by Frenzie** [comment]
This repo represents a means of running LuaJIT-based programs on Android. It's used in KOReader, but just like the KOReader base libraries (a framework of libraries on top of which you can build a reader app) it's not necessarily identical to the one used in front. Usually it won't be too far off but we generally don't update it for every little commit. ^_^
