### ISSUE TITLE
Can't build app on macOS

### ISSUE THREAD

**Issue by nchungdev** [koreader/android-luajit-launcher#362]
I run project on MacOS but it's not working. (I've installed NDK)
MacOS: 12.0.1
<br/>
<img width="1620" alt="Untitled" src="https://user-images.githubusercontent.com/46637152/154844572-7ccfd49c-b6e1-4a09-961f-a8aa869305a6.png">

**Comment by Frenzie** [comment]
You need NDK r15c.

**Comment by nchungdev** [comment]
Tks for ur support, but seem it doesn't seem to work on mac chip M1

**Comment by nchungdev** [comment]
I've tried rebuild on linux (Ubuntu 20.04) and got this issue. I searched all day on internet but still no solution.
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/46637152/155846677-428bfb1b-76ba-42b1-b34f-d5d06b2fd765.png">

**Comment by Frenzie** [comment]
https://github.com/koreader/android-luajit-launcher#starting
