### ISSUE TITLE
Bottom space missing when using camera notch space in my Oppo with ColorOS

### ISSUE THREAD

**Issue by jospalau** [koreader/android-luajit-launcher#387]
After trying to use the camera notch space in my Oppo:
![Screenshot_2022-09-26-20-35-08-52_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/85340/192344138-7cc2499c-ee34-4d05-8081-0740753171f3.jpg)

The bottom is missing:
![Screenshot_2022-09-26-20-32-11-08_1aff61e6bd981aaa4ba9d0245eb6c04f.jpg](https://user-images.githubusercontent.com/85340/192344281-3ca2d3af-6370-4bc3-a028-319397089cc6.jpg)

Missbehaving when turning pages:
![Screenshot_2022-09-26-20-41-48-65_1aff61e6bd981aaa4ba9d0245eb6c04f.jpg](https://user-images.githubusercontent.com/85340/192344452-49fd3c5c-5ad4-4c29-ad92-feed0b9fd081.jpg)

I tried the same in a Galaxy S22 Ultra and it works well. My oppo is running ColorOS 11

**Comment by pazos** [comment]
ColorOS is not that useful. Is this android 13?

**Comment by jospalau** [comment]
> ColorOS is not that useful. Is this android 13?
11 according to the specs:
![Screenshot_2022-09-26-21-22-07-63_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/85340/192351713-fd5ad57b-000e-4bb2-92ab-47add045894d.jpg)

**Comment by pazos** [comment]
mmm...

Does it work fine with autoadapt?

I hope so. 

We're not using android view hierarchy and require a rectangle to draw to. We usually get one just discarding a few pixels, as reported by android itself with their safeInsets.

Hint: if it doesn't work in autoadapt or any other mode and you still want to workaround it please attach a picture of the phone to see how it looks, not a screenshot.

**Comment by jospalau** [comment]
> mmm...
> 
> Does it work fine with autoadapt?
> 
> I hope so. 
> 
> We're not using android view hierarchy and require a rectangle to draw to. We usually get one just discarding a few pixels, as reported by android itself with their safeInsets.
> 
> Hint: if it doesn't work in autoadapt or any other mode and you still want to workaround it please attach a picture of the phone to see how it looks, not a screenshot.

Autoadapt is by default and by default notch space is black in KOReader and all apps. This is how it looks the phone enabling the notch space and whe turning pages the black space down shows/disappears.

![20220926_214044.jpg](https://user-images.githubusercontent.com/85340/192356525-ad936267-c201-457a-a215-75fb82cf784d.jpg)

![20220926_214050.jpg](https://user-images.githubusercontent.com/85340/192356590-003a5cd6-01db-4401-82d1-7fc96af1060c.jpg)

**Comment by pazos** [comment]
yeah, we cannot fix that programatically. Use autoadapt.

I guess you can workaround it with a viewport but I cannot help that much with runtime patches. Feel free to open a discussion in https://github.com/koreader/koreader/discussions.
