### ISSUE TITLE
Can't fully support leaf2 Cn version

### ISSUE THREAD

**Issue by agugu2000** [koreader/android-luajit-launcher#397]
I saw leaf2 supported and tried koreader nightly.
There's still no refresh option.
Developer test shows the driver runs well

Onyx sales leaf2 in china,they name it leaf2_p
Is this the root cause?
![IMG_20221229_041735](https://user-images.githubusercontent.com/119565781/209868376-61e8d73d-8dd8-445c-b50b-e7d7ae37c72c.jpg)

**Comment by pazos** [comment]
> Onyx sales leaf2 in china,they name it leaf2_p
Is this the root cause?

Yes.

It doesn't match device definition: https://github.com/koreader/android-luajit-launcher/pull/389/commits/b426bd4f531a31051d40d49739dc44edfe795084#diff-70eadf1b0a93dd261a4ec1e53148958e4fcfbe339363e707ad9b070d52d6d2b6R303

**Comment by agugu2000** [comment]
here's the test log.Everything goes well,just need a new device definition
[test.log](https://github.com/koreader/android-luajit-launcher/files/10317711/test.log)
> > Onyx sales leaf2 in china,they name it leaf2_p
> > Is this the root cause?
> 
> Yes.
> 
> It doesn't match device definition: [b426bd4#diff-70eadf1b0a93dd261a4ec1e53148958e4fcfbe339363e707ad9b070d52d6d2b6R303](https://github.com/koreader/android-luajit-launcher/commit/b426bd4f531a31051d40d49739dc44edfe795084#diff-70eadf1b0a93dd261a4ec1e53148958e4fcfbe339363e707ad9b070d52d6d2b6R303)
