### ISSUE TITLE
patched device still using previous unsupported driver

### ISSUE THREAD

**Issue by luutuankiet** [koreader/android-luajit-launcher#407]
hi guys, 

Per #406 has been merged to master, I went ahead to clone the Koreader repo and build a custom release for my poke 4 lite. ( `/.koreader release android` as instructed on the main repo)
After installation it seems that koreader still hasn't switched to the patched lights and eink driver; no difference in testing screen refresh, front light adjustments of before & after patch.  

Is there anything else to config on koreader build to specify the new driver ?

FYI here's the compatibility test driver info, isn't any different with Poke4 so all I did on the patch was cloning each Poke4 line to another Poke4lite.

 ---
Onyx
poke4lite

Onyx SDK (lights)
Onyx/Qualcomm

**Comment by Frenzie** [comment]
Did you update the submodule?

**Comment by luutuankiet** [comment]
very likely not. can you point me to it?

**Comment by Frenzie** [comment]
Over in https://github.com/koreader/koreader/tree/e79f161516764c7f0fa7f950275489f3c5c65149/platform/android

You can set the submodule up however you want for ease of development. In your case probably just something like `git pull origin master`.

**Comment by luutuankiet** [comment]
worked like a charm. thanks!
