### ISSUE TITLE
How to compile android-luajit-launcher

### ISSUE THREAD

**Issue by ssyee** [koreader/android-luajit-launcher#411]
android-luajit-launcher compile How to compile android-luajit-launcher? Can I compile it in AndroidStudio? 
I tried to build it in AS and got the following error.
Cause: error when building with ndkBuild using /xxx/android-luajit-launcher/jni/Android.mk: Build command failed.
Error while executing process /xxx/ndk/android-ndk-r15c-linux-x86_64/android-ndk-r15c/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/xxx/android-luajit-launcher/jni/Android.mk NDK_APPLICATION_MK=/xxx/android-luajit-launcher/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=/xxx/android-luajit-launcher/app/build/intermediates/ndkBuild/armFdroidDebug/obj NDK_LIBS_OUT=/xxx/android-luajit-launcher/app/build/intermediates/ndkBuild/armFdroidDebug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/xxx/android-luajit-launcher/jni/luajit/Android.mk:luajit: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /xxx/android-luajit-launcher/jni/luajit/build/armeabi-v7a/lib/libluajit.so exists  or that its path is correct

**Comment by Frenzie** [comment]
See the explanation in the readme: https://github.com/koreader/android-luajit-launcher#starting
