### ISSUE TITLE
Is doing a port for the new mobiscribe wave B&W too difficult?

### ISSUE THREAD

**Issue by raidencup** [koreader/android-luajit-launcher#413]
It runs on an allwinner Cortex-A53 1.5GHz. None of the eink drivers work during testing apart from display brightness control using toleen root. 

The top menu for koreader cannot be triggered either (had to run the test using adb usb debugging as cannot access tools).
Cannot navigate after launching pdf book. 

I can get some help with porting it from a family member. Thanks for your input. 

[test[1].log](https://github.com/koreader/android-luajit-launcher/files/11217780/test.1.log)

**Comment by pazos** [comment]
Nobody knows.

Usually the worst part is dealing with broken APIs and bad behaving devices. Some devices cannot be fixed without OEM/vendor support.

The EPD/lights part is mostly the same on all devices, AFAIK.

You mostly need to document how the system app does to refresh the screen or change light levels, including the methods they're calling. It doesn't require a developer :tm:  but more of a tinkerer/hacker person with the device, time and willing to learn.
