### ISSUE TITLE
building on linux

### ISSUE THREAD

**Issue by CapsAdmin** [koreader/android-luajit-launcher#42]
I'm not at all experienced with android development but this project got me interested to try. 

I downloaded android studio 2.1, installed the NDK from android studio, setup environment variables, spent some time trying to figure out why `android update project --path .` didn't work. `local.properties` seems to want sdk version 19 so I installed that which made it work. Then the `mk-luajit.sh` script didn't execute properly due to some syntax error. I assume it's because it's attempting to run it as a shell script rather than bash (so i added `#!/bin/bash` at the top).

Now I'm stuck at this 
```
./mk-luajit.sh armeabi-v7a
make: Entering directory '/home/caps/android-luajit-launcher/luajit-2.0'
==== Building LuaJIT 2.1.0-beta2 ====
make -C src
make[1]: Entering directory '/home/caps/android-luajit-launcher/luajit-2.0/src'
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make[1]: /home/caps/Android/Sdk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc: Command not found
Makefile:262: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory '/home/caps/android-luajit-launcher/luajit-2.0/src'
Makefile:105: recipe for target 'src/luajit' failed
make: *** [src/luajit] Error 2
make: Leaving directory '/home/caps/android-luajit-launcher/luajit-2.0'
```

I also noticed there's a makefile which does everything the readme wants you to do.

**Comment by houqp** [comment]
Hi @CapsAdmin ,

Thanks for the feedback! Although this project is designed to be a generic launcher, we have only used it with the KOReader build system. So there are definitely things that we missed. Looks like you are very close to get it working ;P

So I think your android cross toolchain is not setup properly. Here is how KOReader sets up the toolchain:

https://github.com/koreader/koreader-base/blob/96331c9da805be4616884b53cc5ced79f81a81b3/Makefile#L136

After the toolchain is installed, make sure `$(ANDROID_TOOLCHAIN)/bin` is in your `PATH`:

https://github.com/koreader/koreader-base/blob/96331c9da805be4616884b53cc5ced79f81a81b3/Makefile.defs#L40

And yes, we do use the apk target directly: 

https://github.com/koreader/koreader/blob/master/Makefile#L307

**Comment by houqp** [comment]
Closing this issue for now. You should be able to fix it by installing NDK and build a toolchain using command similar in: https://github.com/koreader/koreader-base/blob/3792d26a3bec600a5d85b4986b911f96080c5303/Makefile#L142. Then add the toolchain directory to your $PATH.
