### ISSUE TITLE
Add support refresh screen Meebook P78 pro

### ISSUE THREAD

**Issue by panyarazzi** [koreader/android-luajit-launcher#427]
Device info:
Manufacturer: haoqing
Brand: haoqing
Model: q78
Device: q78
Product: rk3566_eink
Hardware: rk30board
Platform: rk356x

Test logs:
[test.log](https://github.com/koreader/android-luajit-launcher/files/12065656/test.log)

**Comment by pazos** [comment]
mmm

> If no driver work

> Wait until somebody writes a driver for that platform. 

> If you want to do the port yourself and need help please open a new ticket in https://github.com/koreader/android-luajit-launcher/issues

I'm going to remove the last sentence from the instructions in https://github.com/koreader/koreader/issues/8482. People who really want to contribute a new driver will hopefully find a way and we will avoid a few tickets here that are not actionable.
