### ISSUE TITLE
tolino page 2

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#455]
Coming from #11264, KOReader works just fine with the `android-arm` apk.
The drivers that are working are "Tolino Ntx" and "Tolino Root" for lights and "Freescale/NTX" for e-ink. The driver test also states `Device already supported, EPD: freescale, Lights: tolino`. The only two minor concerns I have are

1. Both working light drivers have a warmth slider but the device doesn't support warmth.
2. KOReader is unable to enable/disable the frontlight, it can only change the brightness. Toggling the light has to be done outside of KOReader by tapping the android status bar.

<details>
<summary><code>test.log</code></summary>

```
Device info:
Manufacturer: rakuten kobo inc.
Brand: rakutenkobo
Model: tolino
Device: ntx_6sl
Product: ntx_6sl
Hardware: e60qv0
Platform: imx6


Test logs:
```

</details>

The device uses Android 4.4.2 with kernel version `3.0.35-gb5779db-dirty`

_Originally posted by @RubixDev in https://github.com/koreader/koreader/issues/8482#issuecomment-1868903843_

**Comment by pazos** [comment]
> 1. Both working light drivers have a warmth slider but the device doesn't support warmth.

Feel free to submit a patch with a new controller. Just copy the relevant class with a different name, set hasWarmth to false and remove warmth functions.

> 2. KOReader is unable to enable/disable the frontlight, it can only change the brightness. Toggling the light has to be done outside of KOReader by tapping the android status bar.

TolinoRoot controller requires root to toggle frontlight. That's not something fixable. Feel free to play with TolinoNTX controller, see if that works and then change the assigned driver in LightsFactory.kt.

**Comment by RubixDev** [comment]
> Feel free to submit a patch with a new controller. Just copy the relevant class with a different name, set hasWarmth to false and remove warmth functions.

I can try that, I would just like some guidance on how I can test my changes locally.

> TolinoRoot controller requires root to toggle frontlight. That's not something fixable. Feel free to play with TolinoNTX controller, see if that works and then change the assigned driver in LightsFactory.kt.

Ah, TolinoNTX is able to toggle the frontlight. I just didn't realise the driver stays selected after exiting the compat test screen.

**Comment by pazos** [comment]
See https://github.com/koreader/koreader/blob/master/doc/Building.md and https://github.com/koreader/koreader/blob/master/doc/Building_targets.md.

You need to build an APK since you're playing with compiled bytes.

Once you're done setting your environment a simple `./kodev release android` should be enough to produce an APK. You need to sign it (1st example of https://github.com/patrickfav/uber-apk-signer)

**Comment by mergen3107** [comment]
> You need to sign it

Oh, I've never done this. Yet, I was able to install any built debug apks. Is this correct, or should I start signing them too?

**Comment by pazos** [comment]
Debug builds are good just for debugging. They weight a lot, assets extraction is a lot slower and the program is marginally slower as well.

The only thing you get for free with a debug build is a signature. You can get the same signature with the method above (without the requirement of creating your own key) and have a release build, without nonsense.

**Comment by mergen3107** [comment]
I see, thanks! Turns out, I haven't released anything non-debug yet :D
