### ISSUE TITLE
Onyx Palma

### ISSUE THREAD

**Issue by pazos** [koreader/android-luajit-launcher#456]
Device info:
Manufacturer: onyx
Brand: onyx
Model: palma
Device: boox
Product: boox
Hardware: qcom
Platform: bengal

Lights don't work at all; it seems like Palma is using some new method (not cold + warm, but brightness + temperature).
Eink works with Onyx/Qualcomm.

_Originally posted by @CrazyCoder in https://github.com/koreader/koreader/issues/8482#issuecomment-1671581369_

**Comment by hugleo** [comment]
Maybe can work with this: https://github.com/koreader/android-luajit-launcher/pull/436

**Comment by pazos** [comment]
@hugleo: OP can investigate when https://github.com/koreader/android-luajit-launcher/pull/436#issuecomment-1868552149 is addressed ;)

**Comment by pazos** [comment]
Out of date, please repeat the EinkTest
