### ISSUE TITLE
Issue with building on windows 10

### ISSUE THREAD

**Issue by Nathan1852** [koreader/android-luajit-launcher#47]
I tried building this project on windows 10, but when I call ndk build I get an error message:

Android NDK: ERROR: jni/Android.mk:luajit-prebuild: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that jni/luajit-build/armeabi-v7aa/lib/libluajit-5.1 exists or that its path is correct

I checked, and there isn't even a folder jni/luajit-build and I don't know how or where to get it

**Comment by houqp** [comment]
You need to build luajit first, see `compile LuaJIT for your target architecture` section from the README. The default build script hasn't been tested under windows though.
