### ISSUE TITLE
Codacy Permissions

### ISSUE THREAD

**Issue by yparitcher** [koreader/android-luajit-launcher#470]
I got an email from GitHub today that the Codacy GitHub app is requesting additional permissions.

It seems it is being now has access to "Read and write access to checks, commit statuses, issues, organization hooks, pull requests, and repository hooks" And appears to be used only in this repo for the badge. (Which is a broken link). 

Is this still relevant?

Also once i looked i noticed that the GitLocalize App has access to the test data repo for localization. Are we still using this?

We also have apporved the Codacy oath app which does not appear to be used, and CodeHub (a Ios github client).
If we are no longer using them we might want to restrict them similar to how we disabled Travis.

Not a big deal, but i believe there is no need to leave access for unused integrations.

@Frenzie 
@pazos 
@ Not sure / whoever else may have approved or use these?

**Comment by Frenzie** [comment]
I didn't approve anything new, but I do like the  Codacy views.

> Also once i looked i noticed that the GitLocalize App has access to the test data repo for localization. Are we still using this?

I don't think there's any integration that'd be relevant to the test data repo.

> CodeHub (a Ios github client)

Never heard of it.

**Comment by Frenzie** [comment]
Correction, Codacy is the one I switched away from in favor of Codecov.

**Comment by Frenzie** [comment]
Yes, here's a sample commit that came from such static checks.
https://github.com/koreader/android-luajit-launcher/commit/4321d0a1d75d7635c80afeb8b7c50a365d516c91

**Comment by yparitcher** [comment]
So we should probably be able to remove  GitLocalize  & CodeHub.

I will wait a few days to see if anyone else knows if / where they are used.

@NiLuJe 
@poire-z

**Comment by poire-z** [comment]
I don't know anything about this Codacy. No thought or opinion :/

**Comment by pazos** [comment]
@yparitcher: sorry, I missed the notification :p

> And appears to be used only in this repo for the badge. 

Not just for the badge. It does review PR to make sure they're up to standards. See https://app.codacy.com/gh/koreader/android-luajit-launcher/dashboard

**Comment by pazos** [comment]
I mean, I can live without it. But the permissions it requests seems quite necessary to do its job.

**Comment by yparitcher** [comment]
> I mean, I can live without it. But the permissions it requests seems quite necessary to do its job.

I am fine with keeping it, as it does something usefull.
