### ISSUE TITLE
Switch to Gradle

### ISSUE THREAD

**Issue by Frenzie** [koreader/android-luajit-launcher#60]
It's the future… for now. One hopes it won't be discarded a few years down the line. in any case, SDK 26 doesn't work well with the current Ant-based system.

**Comment by Frenzie** [comment]
Here's some info about using Gradle to do dynamic versioning (cf. https://github.com/koreader/koreader/issues/2896#issuecomment-301670883).

https://stackoverflow.com/a/18021756/2470572
https://proandroiddev.com/configuring-android-project-version-name-code-b168952f3323

**Comment by silberzwiebel** [comment]
In fact, the whole koreader android build won't work [with SDK tools greater than 25.3.0](https://askubuntu.com/a/908596) because the `android` command is deprecated, in particular the `android update project` command.

Going through all of this I just found out that AndroidStudio messed up my android-sdk-tools folder. It was only then that I realized that the koreader build script actually downloads it's own android-sdk. It's still not working, but I'm on it.

This [blog article](http://ryanharter.com/blog/2013/07/17/migrating-android-projects-to-gradle/) might also help in migrating to gradle. And, apparently, one can migrate step by step as [gradle allows to use ant](https://docs.gradle.org/current/userguide/ant.html):
> You can use Gradle’s Ant integration as a path for migrating your build from Ant to Gradle. For example, you could start by importing your existing Ant build. Then you could move your dependency declarations from the Ant script to your build file. Finally, you could move your tasks across to your build file, or replace them with some of Gradle’s plugins. This process can be done in parts over time, and you can have a working Gradle build during the entire process.

**Comment by Frenzie** [comment]
That's a minor issue in the sense of upgrading; slightly less so in the sense of maintaining compatibility with older software stacks. See my comment here: https://github.com/koreader/koreader-base/pull/510#discussion_r139290793

> I tossed in this last-minute but it's better to stick with 24 (or at least no higher than `https://dl.google.com/android/repository/tools_r25.2.5-linux.zip`).
>
> It does give you the nice `yes | sdkmanager --licenses` possibility, which on second thought might be somewhat questionable to stick in here, but it deprecates the android command and only prints a deprecated message.
>
> So, for SDK 26 and up, `sdkmanager "build-tools;26.0.1" "platform-tools" "platforms;android-14" "platforms;android-16"`
>
> For lower, `android update sdk -u --filter "platform-tools,build-tools-26.0.1,android-14,android-16"`.

Feel free to work it all out if you like but SDK 26 and all of Android can DIAF as far as I'm concerned. :-P

**Comment by silberzwiebel** [comment]
> That's a minor issue in the sense of upgrading

Because `kodev` downloads it's own, proper sdk version, right?
I suggest to update the main koreader README then because there is one sentence that suggested to that I do have to download SDK and NDK manually:

> A recent version of Android SDK (including platform support for API version 19)/NDK, ant, openjdk-8-jdk and p7zip-full are needed in order to build KOReader for Android devices.

Should I open a pull request for this or do you want to change this on your own?

**Comment by Frenzie** [comment]
`kodev` is merely a convenience wrapper; you can override it with whatever you like for testing purposes or just because you already have one or more of those monstrosities installed. But yes, I presume that particular sentence was written in 2014. (And the automatic SDK setup part wasn't completely finished until I added it a couple of weeks ago.)

Anyway, something like this?

> The KOReader Android build requires `ant`, `openjdk-8-jdk` and `p7zip-full`. A compatible version of the Android NDK and SDK will be downloaded automatically by `kodev build android` if no NDK or SDK is provided in environment variables. For that purpose you can use `NDK=/ndk/location SDK=/sdk/location ./kodev build android`.

**Comment by silberzwiebel** [comment]
Sounds perfect!

**Comment by pazos** [comment]
Migrating the whole setup to Android Studio:

1. write a cmake to build luajit
2. write a cmake to build the nativeActivity
3. create a new android(gradle) project with an empty activity
4. copy our java code overriding the generated mainactivity
5. edit gradle to build libraries as part of our project
6. make sure to change application assets path to add application assets to apk bundle
7. port our ant hooks to gradle
8. (optional) move all android build stuff to a gradle task. So people importing the project on android studio can build the whole thing without kodev.

**Comment by Frenzie** [comment]
On 1) I think we can save a few hours by looking around a little, e.g., [here](https://github.com/torch/luajit-rocks/blob/2c7496b905f6f972673effda4884766433b7583b/luajit-2.1/CMakeLists.txt) is one that looks decent.

Also interesting, [this](https://cliutils.gitlab.io/modern-cmake/) shows how CMake isn't quite the CMake I mostly dislike anymore. Although it doesn't seem to address anything I dislike about it from the perspective of a user who just wants to cross-compile a piece of software they came across. Generally not a problem with Autotools regardless whether the dev thought of it or not… Somewhat similar story with Meson… but CMake… grmbl, grmbl. :-)


Instead of our current CMake 2.8 requirement, in principle we can easily bump that to 3.5 these days, if there is a compelling reason to. (There are plenty, but doing it before wanting to actually use a newer feature would be rather silly. ;-) )

Also see CMake 3.11's [FetchContent](https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html), which could obsolete a bunch of stuff in base (if it works properly; haven't tested). More of a mid- to long-term thing of course.

I played around with Meson a little and I'm quite enthusiastic about it. But newer CMake resolves a lot of issues, and gradual improvements are easier than rewrites. (Plus there's that native IDE support like in Android Studio.)

**Comment by pazos** [comment]
> On 1) I think we can save a few hours by looking around a little, e.g., here is one that looks decent.

:+1:  I will try this weekend!

btw, I don't understand why lzma is not statically linked agaisnt stdc++. the rest of libraries don't rely on libstd++. Any idea @Frenzie ?

**Comment by Frenzie** [comment]
I couldn't say.

**Comment by pazos** [comment]
An update: we need a gradle build in order to use aar libraries (like appcompat ones).

Appcompat support (at least v4, but v7 or v13 are better because our minimum target is api14) is a prerequisite to use runtime permissions and thus building for an api higher than 22.
